version: '3.8'

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        - FASTAPI_PORT
    volumes:
      - ./app:/app
      - ./frontend:/frontend
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - mlflow
      - database
    networks:
      - one_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  database:
    image: postgres:16.2
    environment:
      - ENVIROMENT=$ENVIRONMENT
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_INITDB_ARGS=--data-checksums
    container_name: database
    restart: always
    volumes:
      - ./database/postgres-$ENVIRONMENT.conf:/etc/postgresql/postgresql.conf
      - ./database/init_scripts:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"
    networks:
      - one_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: ["streamlit", "run", "Home.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    volumes:
      - ./frontend:/frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - app
      - database
      - mlflow
    networks:
      - one_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.2
    command: ["mlflow", "server", "--backend-store-uri", "${MLFLOW_STORE_URI}", "--default-artifact-root", "${MLFLOW_ARTIFACT_URI}", "--host", "${MLFLOW_TRACKING_HOST}", "--port", "${MLFLOW_TRACKING_PORT}"]
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - MLFLOW_TRACKING_HOST=$MLFLOW_TRACKING_HOST
      - MLFLOW_TRACKING_PORT=$MLFLOW_TRACKING_PORT
      - MLFLOW_ARTIFACT_URI=$MLFLOW_ARTIFACT_URI
      - MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI
      - MLFLOW_STORE_URI=$MLFLOW_STORE_URI
    depends_on:
      - database
    ports:
      - "5000:5000"
    networks:
      - one_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  one_network:
    driver: bridge
  