version: '3.8'

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app_engine
    volumes:
      - ./app:/app
      - ./frontend:/frontend
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - mlflow
      - database
    networks:
      - one_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: postgres:16.2
    container_name: database_server
    env_file:
      - .env
    volumes:
      - ./database/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./database/init_scripts:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5435:5432"
    networks:
      - one_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5435/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend_server
    env_file:
      - .env
    command: ["streamlit", "run", "Home.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    volumes:
      - ./frontend:/frontend
    ports:
      - "8501:8501"
    depends_on:
      - app
      - database
      - mlflow
    networks:
      - one_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.2
    command: ["mlflow", "server",
            "--backend-store-uri", "${MLFLOW_STORE_URI}",
            "--default-artifact-root", "${MLFLOW_ARTIFACT_URI}",
            "--host", "${MLFLOW_TRACKING_HOST}",
            "--port", "${MLFLOW_TRACKING_PORT}"]
    env_file:
      - .env
    container_name: mlflow_server
    depends_on:
      - database
    ports:
      - "5000:5000"
    networks:
      - one_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  one_network:
    driver: bridge
