postgres -c "CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';"
postgres -c "CREATE USER $MLFLOW_TRACKING_USER WITH PASSWORD '$MLFLOW_TRACKING_PASSWORD';"
postgres -c "CREATE DATABASE $MLFLOW_TRACKING_NAME;"
postgres -c "GRANT ALL PRIVILEGES ON DATABASE $MLFLOW_TRACKING_NAME TO $MLFLOW_TRACKING_USER;"

mlflow db upgrade postgresql://$MLFLOW_TRACKING_USER:$MLFLOW_TRACKING_PASSWORD@$MLFLOW_TRACKING_HOST:$MLFLOW_TRACKING_PORT/$MLFLOW_TRACKING_NAME