name: Docker Deploy

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: [self-hosted]
    env:
      PYTHONDONTWRITEBYTECODE: 1
      LOG_LEVEL: ${{ github.LOG_LEVEL }}
      HF_MODEL_NAME: ${{ github.HF_MODEL_NAME }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      APP_URL_BASE: ${{ github.APP_URL_BASE }}
      WORKERS_PER_CORE: ${{ secrets.WORKERS_PER_CORE }}
      MLFLOW_TRACKING_URI: ${{ github.MLFLOW_TRACKING_URI }}
      MLFLOW_STORE_URI: ${{ github.MLFLOW_STORE_URI }}
      MLFLOW_PORT: ${{ github.MLFLOW_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Display User
        run: |
          echo "Running as user: $(whoami)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Create .env file from envs
        run: |
          echo "Running as user: $(whoami)"
          echo "LOG_LEVEL=${LOG_LEVEL}" >> .env
          echo "HF_MODEL_NAME=${HF_MODEL_NAME}" >> .env
          echo "HF_TOKEN=${HF_TOKEN}" >> .env
          echo "APP_URL_BASE=${APP_URL_BASE}" >> .env
          echo "WORKERS_PER_CORE=${WORKERS_PER_CORE}" >> .env
          echo "MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}" >> .env
          echo "MLFLOW_STORE_URI=${MLFLOW_STORE_URI}" >> .env
          echo "MLFLOW_PORT=${MLFLOW_PORT}" >> .env
          echo "POSTGRES_USER=${POSTGRES_USER}" >> .env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
          echo "POSTGRES_DB=${POSTGRES_DB}" >> .env

      - name: Bring down Docker Compose services
        run: docker-compose down || true # Ignore errors if services are not running

      - name: Bring up Docker Compose services and verify
        run: |
          docker-compose up --build --detach --remove-orphans

      - name: Bring down Docker Compose services
        if: github.event_name == 'pull_request'
        run: docker-compose down || true # Ignore errors if services are not running
